markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-coffeescript
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  - scope:
      type: posts
    values:
      permalink: /posts/:title/
      layout: post
      css: post
  - scope:
      type: pages
    values:
      css: page
      layout: page
