markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-coffeescript
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
defaults:
  - scope:
      type: posts
    values:
      permalink: posts/:title/
      layout: post
  - scope:
      type: pages
    values:
      layout: page
